name: Destroy Pulumi Stack

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557690603426:role/khatoon-pulumi-role
          aws-region: ${{ secrets.AWS_REGION }}
          audience: aws:Julie0418 # Updated audience to match your AWS configuration

      - name: Install Dependencies
        working-directory: ./mypulumi
        run: npm install

      - uses: pulumi/actions@v6
        with:
          command: destroy
          stack-name: Julie0418/mypulumi/dev # When using an individual account, only use stack-name.
          work-dir: ./mypulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}